[book]
title = "Build You A Tiger Compiler"
authors = ["Garret Wassermann"]
language = "en"
multilingual = false
src = "doc"

[rust]
edition = "2021"

[build]
build-dir = "book"
create-missing = false

[output.html]
curly-quotes = true
mathjax-support = true
git-repository-url = "https://github.com/gwasser/lambdatiger"
git-repository-icon = "fa-github"

[output.html.search]
limit-results = 15


